"""HTML rendering of a QualityReport — self-contained single file with inline CSS."""

from __future__ import annotations

import math
from html import escape

from doppel.quality.aggregate import QualityReport

_CSS = """
* { box-sizing: border-box; }
body { font-family: ui-sans-serif, system-ui, sans-serif; max-width: 960px; margin: 2.5rem auto; padding: 0 1.25rem; color: #1f2937; }
h1 { margin-bottom: 0.25rem; }
h2 { margin-top: 2.5rem; border-bottom: 1px solid #e5e7eb; padding-bottom: 0.25rem; }
.subtitle { color: #6b7280; margin-bottom: 1.5rem; }
table { border-collapse: collapse; width: 100%; font-size: 0.95rem; margin: 0.5rem 0 1rem; }
th, td { padding: 0.45rem 0.7rem; border-bottom: 1px solid #e5e7eb; text-align: left; }
th { background: #f9fafb; font-weight: 600; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
.summary { background: #f3f4f6; padding: 0.5rem 0.8rem; border-radius: 6px; display: inline-block; font-weight: 600; }
.warn { background: #fef3c7; padding: 0.75rem 1rem; border-left: 3px solid #f59e0b; border-radius: 4px; margin: 0.75rem 0; color: #78350f; }
.footer { color: #9ca3af; font-size: 0.85rem; margin-top: 3rem; }
"""


def to_html(report: QualityReport) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>doppel quality report</title>
<style>{_CSS}</style>
</head>
<body>
<h1>doppel quality report</h1>
<p class="subtitle">
  <strong>{escape(report.real_label)}</strong> ({report.real_rows} rows)
  vs.
  <strong>{escape(report.synth_label)}</strong> ({report.synth_rows} rows)
</p>

<h2>Marginals</h2>
<p>Per-column similarity. Lower = closer to the real distribution. 0 means identical.</p>
<p class="summary">average score: {_fmt(report.avg_marginal)}</p>
{_marginals_table(report)}
{_verbatim_warning(report)}
{_calendar_fidelity_section(report)}
{_issues(report)}

<h2>Correlation structure</h2>
<p>How well the synthetic data preserves pairwise associations across columns.</p>
<table>
  <tr><th>columns compared</th><td class="num">{len(report.correlations.columns)}</td></tr>
  <tr><th>Frobenius distance (normalised)</th><td class="num">{_fmt(report.correlations.frobenius_distance)}</td></tr>
</table>

<h2>Privacy — distance to closest record</h2>
<div class="warn">
  Heuristic, not a formal privacy guarantee. Differential privacy lands post-v1.
  Low percentiles mean some synthetic rows are close to real rows — investigate.
</div>
<table>
  <tr><th>rows compared</th><td class="num">{report.privacy.n_synth} synth vs {report.privacy.n_real} real</td></tr>
  <tr><th>features (after encoding)</th><td class="num">{report.privacy.n_features}</td></tr>
  <tr><th>min DCR</th><td class="num">{_fmt(report.privacy.min_distance)}</td></tr>
  <tr><th>DCR p5</th><td class="num">{_fmt(report.privacy.percentile_5)}</td></tr>
  <tr><th>DCR p25</th><td class="num">{_fmt(report.privacy.percentile_25)}</td></tr>
  <tr><th>DCR p50 (median)</th><td class="num">{_fmt(report.privacy.percentile_50)}</td></tr>
  <tr><th>DCR mean</th><td class="num">{_fmt(report.privacy.mean_distance)}</td></tr>
</table>

<p class="footer">generated by doppel</p>
</body>
</html>
"""


def _fmt(v: float) -> str:
    """Render a float as 4-decimal text, or '—' when it isn't finite."""
    return f"{v:.4f}" if math.isfinite(v) else "&mdash;"


def _marginals_table(report: QualityReport) -> str:
    if not report.marginals:
        return "<p><em>no comparable columns</em></p>"
    rows = "\n".join(
        f"<tr>"
        f"<td>{escape(m.column)}</td>"
        f"<td>{escape(m.type.value)}</td>"
        f"<td>{escape(m.metric)}</td>"
        f"<td class='num'>{_fmt(m.value)}</td>"
        f"<td class='num'>{m.null_rate_real * 100:.1f}%</td>"
        f"<td class='num'>{m.null_rate_synth * 100:.1f}%</td>"
        f"<td class='num'>{_verbatim_cell(m.verbatim_rate)}</td>"
        f"</tr>"
        for m in sorted(report.marginals, key=lambda m: m.value, reverse=True)
    )
    return (
        "<table>"
        "<tr>"
        "<th>column</th><th>type</th><th>metric</th>"
        "<th class='num'>score</th>"
        "<th class='num'>null% real</th><th class='num'>null% synth</th>"
        "<th class='num'>verbatim%</th>"
        "</tr>"
        f"{rows}"
        "</table>"
    )


def _verbatim_cell(rate: float | None) -> str:
    if rate is None:
        return ""
    return f"{rate * 100:.1f}%"


def _verbatim_warning(report: QualityReport) -> str:
    """Mirror the terminal renderer's yellow block: any TEXT column with verbatim>0
    is a free-text leakage signal that stakeholders viewing the HTML should see."""
    leaks: list[tuple[str, float]] = [
        (m.column, m.verbatim_rate)
        for m in report.marginals
        if m.verbatim_rate is not None and m.verbatim_rate > 0
    ]
    if not leaks:
        return ""
    items = "\n".join(
        f"<li><code>{escape(column)}</code>: "
        f"{rate * 100:.1f}% of synth values are verbatim copies</li>"
        for column, rate in leaks
    )
    return (
        '<div class="warn"><strong>Text columns resampled with replacement.</strong>'
        " Synthetic values may be verbatim copies of the real data:"
        f"<ul>{items}</ul></div>"
    )


def _calendar_fidelity_section(report: QualityReport) -> str:
    """One per-feature KS table per datetime column, under a "Calendar fidelity" heading."""
    if not report.calendar_fidelity:
        return ""
    blocks: list[str] = [
        "<h2>Calendar fidelity</h2>",
        "<p>Per-feature KS distance between real and synth temporal patterns "
        "(hour-of-day, day-of-week, month-of-year). Lower is better.</p>",
    ]
    for column, scores in report.calendar_fidelity.items():
        rows = "\n".join(
            f"<tr><td>{escape(s.feature)}</td>"
            f"<td class='num'>{_fmt(s.value)}</td>"
            f"<td class='num'>{s.n_real}</td>"
            f"<td class='num'>{s.n_synth}</td></tr>"
            for s in scores
        )
        blocks.append(
            f"<h3><code>{escape(column)}</code></h3>"
            "<table>"
            "<tr><th>feature</th><th class='num'>KS</th>"
            "<th class='num'>n real</th><th class='num'>n synth</th></tr>"
            f"{rows}"
            "</table>"
        )
    return "\n".join(blocks)


def _issues(report: QualityReport) -> str:
    if not report.dtype_mismatches and not report.invariant_issues:
        return ""
    blocks: list[str] = ["<h2>Likely issues</h2>"]
    if report.dtype_mismatches:
        rows = "\n".join(
            "<tr>"
            f"<td>{escape(i.column)}</td>"
            f"<td>{escape(i.real_dtype)}</td>"
            f"<td>{escape(i.synth_dtype)}</td>"
            "</tr>"
            for i in report.dtype_mismatches
        )
        blocks.append(
            "<h3>Dtype mismatches</h3>"
            "<table>"
            "<tr><th>column</th><th>real dtype</th><th>synth dtype</th></tr>"
            f"{rows}"
            "</table>"
        )
    if report.invariant_issues:
        rows = "\n".join(
            "<tr>"
            f"<td>{escape(i.label)}</td>"
            f"<td class='num'>{i.real_violations}</td>"
            f"<td class='num'>{i.synth_violations}</td>"
            "</tr>"
            for i in report.invariant_issues
        )
        blocks.append(
            "<h3>Likely count invariant drifts</h3>"
            "<table>"
            "<tr><th>relationship</th><th class='num'>real violations</th>"
            "<th class='num'>synth violations</th></tr>"
            f"{rows}"
            "</table>"
        )
    return "\n".join(blocks)
