"""HTML rendering of a QualityReport — self-contained single file with inline CSS."""

from __future__ import annotations

from html import escape

from doppel.quality.aggregate import QualityReport

_CSS = """
* { box-sizing: border-box; }
body { font-family: ui-sans-serif, system-ui, sans-serif; max-width: 960px; margin: 2.5rem auto; padding: 0 1.25rem; color: #1f2937; }
h1 { margin-bottom: 0.25rem; }
h2 { margin-top: 2.5rem; border-bottom: 1px solid #e5e7eb; padding-bottom: 0.25rem; }
.subtitle { color: #6b7280; margin-bottom: 1.5rem; }
table { border-collapse: collapse; width: 100%; font-size: 0.95rem; margin: 0.5rem 0 1rem; }
th, td { padding: 0.45rem 0.7rem; border-bottom: 1px solid #e5e7eb; text-align: left; }
th { background: #f9fafb; font-weight: 600; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
.summary { background: #f3f4f6; padding: 0.5rem 0.8rem; border-radius: 6px; display: inline-block; font-weight: 600; }
.warn { background: #fef3c7; padding: 0.75rem 1rem; border-left: 3px solid #f59e0b; border-radius: 4px; margin: 0.75rem 0; color: #78350f; }
.footer { color: #9ca3af; font-size: 0.85rem; margin-top: 3rem; }
"""


def to_html(report: QualityReport) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>doppel quality report</title>
<style>{_CSS}</style>
</head>
<body>
<h1>doppel quality report</h1>
<p class="subtitle">
  <strong>{escape(report.real_label)}</strong> ({report.real_rows} rows)
  vs.
  <strong>{escape(report.synth_label)}</strong> ({report.synth_rows} rows)
</p>

<h2>Marginals</h2>
<p>Per-column similarity. Lower = closer to the real distribution. 0 means identical.</p>
<p class="summary">average score: {report.avg_marginal:.4f}</p>
{_marginals_table(report)}

<h2>Correlation structure</h2>
<p>How well the synthetic data preserves pairwise associations across columns.</p>
<table>
  <tr><th>columns compared</th><td class="num">{len(report.correlations.columns)}</td></tr>
  <tr><th>Frobenius distance (normalised)</th><td class="num">{report.correlations.frobenius_distance:.4f}</td></tr>
</table>

<h2>Privacy — distance to closest record</h2>
<div class="warn">
  Heuristic, not a formal privacy guarantee. Differential privacy lands post-v1.
  Low percentiles mean some synthetic rows are close to real rows — investigate.
</div>
<table>
  <tr><th>rows compared</th><td class="num">{report.privacy.n_synth} synth vs {report.privacy.n_real} real</td></tr>
  <tr><th>features (after encoding)</th><td class="num">{report.privacy.n_features}</td></tr>
  <tr><th>min DCR</th><td class="num">{report.privacy.min_distance:.4f}</td></tr>
  <tr><th>DCR p5</th><td class="num">{report.privacy.percentile_5:.4f}</td></tr>
  <tr><th>DCR p25</th><td class="num">{report.privacy.percentile_25:.4f}</td></tr>
  <tr><th>DCR p50 (median)</th><td class="num">{report.privacy.percentile_50:.4f}</td></tr>
  <tr><th>DCR mean</th><td class="num">{report.privacy.mean_distance:.4f}</td></tr>
</table>

<p class="footer">generated by doppel</p>
</body>
</html>
"""


def _marginals_table(report: QualityReport) -> str:
    if not report.marginals:
        return "<p><em>no comparable columns</em></p>"
    rows = "\n".join(
        f"<tr>"
        f"<td>{escape(m.column)}</td>"
        f"<td>{m.type.value}</td>"
        f"<td>{m.metric}</td>"
        f"<td class='num'>{m.value:.4f}</td>"
        f"<td class='num'>{m.null_rate_real * 100:.1f}%</td>"
        f"<td class='num'>{m.null_rate_synth * 100:.1f}%</td>"
        f"</tr>"
        for m in report.marginals
    )
    return (
        "<table>"
        "<tr>"
        "<th>column</th><th>type</th><th>metric</th>"
        "<th class='num'>score</th>"
        "<th class='num'>null% real</th><th class='num'>null% synth</th>"
        "</tr>"
        f"{rows}"
        "</table>"
    )
